version: 2.1
workflows:
  main:
    jobs:
      - test-functions
      - build_and_deploy:
          requires:
            - test-functions

jobs:
  test-functions:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: echo ${ENV} > ~/.env
      - run: yarn run jest

  build_and_deploy:
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'deployしたい'
